### ISSUE TITLE
Wiki install for RPi core issues

### ISSUE THREAD

**Issue by graber65** [dpoulson/r2_control#60]
with the new Raspberry pi image 2017-11-29-raspbian-stretch, php5 and libapache2-mod-php5 are no longer available. 
they have been replaced with php7.0 and libapache2-mod-php7.0.
the Wiki for Raspberry Pi Core needs to updated to reflect this change.
since I am not sure your php code will work with the new php version I will not update your Wiki.
I

**Comment by dpoulson** [comment]
Documentation updated.
