### ISSUE TITLE
missing image contorlers/www

### ISSUE THREAD

**Issue by graber65** [dpoulson/r2_control#61]
controllers/www/body.php references an image
line 41 img width=400 border=0 src="Body.jpg"
the image does not appear to be in the be in the directory, and shows as missing on the web page.

**Comment by dpoulson** [comment]
Very much a known issue. I've not got round to drawing anything for it, and I'm not much of an artist at the best of times. 

The web interface is only there for quick testing, so has never been a high priority.

**Comment by dpoulson** [comment]
Image added
