### ISSUE TITLE
Requirements.txt update

### ISSUE THREAD

**Issue by l0rdnic0** [dpoulson/r2_control#97]
Hello,

I was wondering if you planned on updating the requirements.txt document to reflect new packages for fresh installs? It seams as if pygame and some other versions error out even after manually setting the current version with pip.

**Comment by dpoulson** [comment]
Yes, I noticed the other week on a fresh install that the install document was a bit out of date for recent PiOS versions. I'll be doing another test install this week hopefully and will update the docs.

**Comment by dpoulson** [comment]
Updated the requirements.txt and also the wiki for installing some extra packages.
